[package]
name = "matplotrs_amethyst_backend"
version = "0.1.0"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]

[dependencies]
amethyst = "0.6"
matplotrs_backend = { path = "../backend" }
